### ISSUE TITLE
why not .tex?

### ISSUE THREAD

**Issue by mrelarsen** [azu/vscode-read-aloud-text#4]
Hello,
Why is it limited to .txt and markdown?
Why is it not possible for it to read from a .tex? it should be just as readable as a .txt

**Comment by azu** [comment]
vscode-read-aloud-text want to read parsable format.
The purpose is that skip unreasonbale text like CodeBlock
It is different with original https://github.com/mattbierner/vscode-speech.


Note: It is possible that we can support latex using
https://www.npmjs.com/package/textlint-plugin-latex2e
If you want do, please submit pull reuqest.
